---
output:
  md_document:
    variant: markdown_github
---


```{r}

library(tidyverse)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
```


```{r, include=FALSE}

# Create Texevier templates for questions 1 to 4 

Texevier::create_template(directory = "/Users/riazpaleker/Documents/Mcom Economics/Data Science/R/22854843_Exam/22854843_Exam", template_name = "Question1")

Texevier::create_template(directory = "/Users/riazpaleker/Documents/Mcom Economics/Data Science/R/22854843_Exam/22854843_Exam", template_name = "Question2")

Texevier::create_template(directory = "/Users/riazpaleker/Documents/Mcom Economics/Data Science/R/22854843_Exam/22854843_Exam", template_name = "Question3")

Texevier::create_template(directory = "/Users/riazpaleker/Documents/Mcom Economics/Data Science/R/22854843_Exam/22854843_Exam", template_name = "Question4")

```


```{r,include=FALSE}


#Q2
source("code/metallic_album_popular.R")
source("code/coldplay_album_popular.R")
source("code/album_summary_table.R")
source("code/regress_metallica.R")
source("code/regress_coldplay.R")

#Q3
source("code/Aid_alloc_plot.R")
source("code/Aid_Commit_plot.R")
source("code/combine_plot.R")

#Q4
source("code/GDP_plot.R")
source("code/GDPvMedal.R")
source("code/Dominance_plot.R")
source("code/overperform_summer.R")
source("code/overperform_winter.R")

```

# Question One


```{r}
#Q1: Source
source("code/name_persistence.R")
source("code/Names_Artists.R")
source("code/change_billboard.R")
```

