---
title: "Helping You Write Academic Papers in R using Texevier"
documentclass: elsarticle
Thesis_FP: false
output:
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: true
    template: Tex/TexDefault.txt
    fig_width: 3.5
    fig_height: 3.5
Author1: Jane Doe^[__Contributions:__  \newline _The authors would like to thank no
  institution for money donated to this project. Thank you sincerely._]
Ref1: Some Institution, Cape Town, South Africa
Email1: nfkatzke\@gmail.com
Author2: John Smith
Ref2: Some other Institution, Cape Town, South Africa
Email2: John\@gmail.com
CommonAffiliation_12: true
Author3: John Doe
Email3: Joe\@gmail.com
CorrespAuthor_1: true
keywords: Multivariate GARCH \sep Kalman Filter \sep Copula
JELCodes: L250 \sep L100
BottomRFooter: \footnotesize Page \thepage
addtoprule: true
addfootrule: true
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: true
linenumbers: false
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: true
Journal: Journal of Finance
toc: false
numbersections: true
fontsize: 11pt
linestretch: 1.2
link-citations: true
AddTitle: true
abstract: null
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}

if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

alloc <- read.csv("./data/Ukraine_Aid/Financial Allocations.csv")
commit <- read.csv("./Data/Ukraine_Aid/Financial Commitments.csv")
```

```{r, include=FALSE}
# all my functions to be called
source("code/Aid_alloc_plot.R")
source("code/Aid_Commit_plot.R")
source("code/combine_plot.R")
```



```{r, echo=FALSE}
Humanatarian_Aid_alloc_plot = Aid_alloc(alloc)
Humanatarian_Aid_alloc_plot
```

```{r, echo=FALSE}
Humanatarian_Aid_Commit_plot = Aid_commit(commit)
Humanatarian_Aid_Commit_plot
```

```{r, echo=FALSE, warning=FALSE}
combined_plots = combine_plots(alloc,commit)
combined_plots
```



