---
title: "Helping You Write Academic Papers in R using Texevier"
documentclass: elsarticle
Thesis_FP: false
output:
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: true
    template: Tex/TexDefault.txt
    fig_width: 3.5
    fig_height: 3.5
Author1: Jane Doe^
Ref1: Some Institution, Cape Town, South Africa
Email1: nfkatzke\@gmail.com
Author2: John Smith
Ref2: Some other Institution, Cape Town, South Africa
Email2: John\@gmail.com
CommonAffiliation_12: true
Author3: John Doe
Email3: Joe\@gmail.com
CorrespAuthor_1: true
keywords: Multivariate GARCH \sep Kalman Filter \sep Copula
JELCodes: L250 \sep L100
BottomRFooter: \footnotesize Page \thepage
addtoprule: true
addfootrule: true
margin: 2.3
bottom: 2
top: 2.5
HardSet_layout: true
linenumbers: false
bibliography: Tex/ref.bib
csl: "Tex/harvard-stellenbosch-university.csl"
RemovePreprintSubmittedTo: true
Journal: Journal of Finance
toc: false
numbersections: true
fontsize: 11pt
linestretch: 1.2
link-citations: true
AddTitle: true
abstract: |
  Abstract to be written here. The abstract should not be too long and should provide the reader with a good understanding what you are writing about. Academic papers are not like novels where you keep the reader in suspense. To be effective in getting others to read your paper, be as open and concise about your findings here as possible. Ideally, upon reading your abstract, the reader should feel he / she must read your paper in entirety.
---

<!-- First: Set your default preferences for chunk options: -->

<!-- If you want a chunk's code to be printed, set echo = TRUE. message = FALSE stops R printing ugly package loading details in your final paper too. I also suggest setting warning = FALSE and checking for warnings in R, else you might find ugly warnings in your paper. -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.width = 6, fig.height = 5, fig.pos="H", fig.pos = 'H')

if(!require("tidyverse")) install.packages("tidyverse")
library(tidyverse)

winter <- readRDS("./Data/olympics/winter.rds") 
summer <- readRDS("./Data/olympics/summer.rds") 
GDP <- readRDS("./Data/olympics/GDP.rds")
```


```{r, include=FALSE}

source("code/GDP_plot.R")
source("code/GDPvMedal.R")
source("code/Dominance_plot.R")
source("code/overperform_summer.R")
source("code/overperform_winter.R")

```



<!-- ############################## -->
<!-- # Start Writing here: -->
<!-- ############################## -->

# Introduction \label{Introduction}


```{r, echo=FALSE, fig.width=8}
GDP_plot =GDP_per_capita(GDP,summer)
GDP_plot
```

```{r,echo=FALSE, fig.width=8}
point_olympic_plot <- GDP_per_capita_medal(GDP,summer)
point_olympic_plot
```


```{r,echo=FALSE, fig.width=8, warning=FALSE, message=FALSE}
combined_dominance_plot <- dominance_plot(summer,winter)
grid::grid.draw(combined_dominance_plot)
```

```{r, fig.height=7, fig.width=8, warning=FALSE, echo=FALSE}
gdp_medal_summer_plot <- over_perform_summer(GDP,summer)
gdp_medal_summer_plot

```


```{r,fig.height=7, fig.width=8, warning=FALSE, echo=FALSE}
gdp_medal_winter_plot <- over_perform_winter(GDP,winter)
gdp_medal_winter_plot
```



